POST http://localhost:8000/api/images/addimg HTTP/1.1
Content-Type: application/json
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYzlmNzdmYjQ5NWU3ODY0NjU5MDk1OCIsImlhdCI6MTY0MDY0MTcxMSwiZXhwIjoxNjQwNjQzNTExfQ._9RvXEYIcLz6Or91DGlQc7wWjAiEJuunf4kQWEDDLf8

{
  "image": "",
  "author": ""
}
###
GET http://localhost:8000/api/images HTTP/1.1
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYzlmNzdmYjQ5NWU3ODY0NjU5MDk1OCIsImlhdCI6MTY0MDY0MjE1MSwiZXhwIjoxNjQwNjQzOTUxfQ._EMmQDAPSSmunvr0CYC-MtTmTNdtUVGLiSnTKdXKmnI

### 
DELETE http://localhost:8000/api/images/remove/61ca34bc8a5d4e97f5680c44 HTTP/1.1
access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYzlmNzdmYjQ5NWU3ODY0NjU5MDk1OCIsImlhdCI6MTY0MDY0MjE1MSwiZXhwIjoxNjQwNjQzOTUxfQ._EMmQDAPSSmunvr0CYC-MtTmTNdtUVGLiSnTKdXKmnI
